{{- if and .Values.ingress.enabled .Values.ingress.tls -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "lobu.fullname" . }}-redirect-https
  namespace: {{ .Values.kubernetes.namespace }}
  labels:
    {{- include "lobu.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
